[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/timetable"
  to = "/.netlify/functions/icalHandler"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/icalHandler"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
