[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/timetable"
  to = "/.netlify/functions/icalHandler"
  status = 200

[[redirects]]
  from = "/:date"
  to = "/.netlify/functions/icalHandler?date=:date"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/icalHandler"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
