[build]
functions = "netlify/functions"

[dev]
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/timetable"
to = "/.netlify/functions/icalHandler"
status = 200

[[redirects]]
from = "/:date"
to = "/.netlify/functions/icalHandler?date=:date"
status = 200

# Multi-account endpoints
[[redirects]]
from = "/ical/:person"
to = "/.netlify/functions/multi/ical/:person"
status = 200

[[redirects]]
from = "/json/:person"
to = "/.netlify/functions/multi/json/:person"
status = 200

# Optional: list accounts (uncomment if implementing /accounts logic in multi.js)
# [[redirects]]
#   from = "/accounts"
#   to = "/.netlify/functions/multi/accounts"
#   status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
