[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/generate-ical"
  to = "/.netlify/functions/generateTimetableIcal"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/generateTimetableIcal"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
